### ISSUE TITLE
写真のプレビュー表示

### ISSUE THREAD

**Issue by ShuheiGotou** [wmikefish/ngs_moc1#5]
# What/Why
ユーザは投稿する写真のプレビューを見ることができる。
写真の誤投稿を防ぐため。
# Acceptance Criteria
- [x] 選択した写真がプレビュー表示されていること
- [x] 画像ファイル以外は表示されないこと
# Reference
[プレビュー表示する方法(jQuery版)](http://qiita.com/kon_yu/items/f98df7ac826e7c36cc6c)
# ToDo
- [x] Referenceを参考にjqueryを実装する
- [x] PCで動作確認
- [x] スマホで動作確認
- [x] 画像ファイル以外を選択し動作確認

**Comment by wmikefish** [comment]
完了。。。。
