### ISSUE TITLE
位置情報を一度取得

### ISSUE THREAD

**Issue by snakamae** [wmikefish/ngs_moc1#8]
# What/Why
-ユーザは困りごとを投稿するときに、位置情報も追加することができる。
-それによって、困りごとが発生した場所を特定することができる。

# Acceptance Criteria
-困りごとを投稿したら、その時の位置情報が取得されること
-取得された位置情報がデータベースに保存されること

# Reference
[Geocoderのレポジトリー](https://github.com/alexreisner/geocoder)
[google geocoding APIの使い方](https://syncer.jp/how-to-use-geocoding-api)

# ToDo
- [x] ジェムの導入
- [x] 位置情報を取得する
- [x] 位置情報を保存する
- [x] マップが表示される

**Comment by TetsuyaNegishi** [comment]
google map APIのKEYをあとで配ります。
KEYがないとmapが正しく動きません。

**Comment by TetsuyaNegishi** [comment]
#9 で完成しました。
